# Generated by Django 5.0.1 on 2024-03-29 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-id"]},
        ),
    ]
